# Generated by Django 3.1.4 on 2020-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('nursery', 'Nursery')], max_length=10),
        ),
    ]
