# Generated by Django 3.1.4 on 2020-12-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201228_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
