# Generated by Django 3.1.4 on 2020-12-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201228_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='userss', max_length=255, unique=True),
        ),
    ]
