# Generated by Django 3.1.4 on 2020-12-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
