# Generated by Django 3.1.4 on 2020-12-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='nursery',
            new_name='added_by',
        ),
    ]
