# Generated by Django 3.1.4 on 2020-12-30 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('order_status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='In-Progress', max_length=255)),
                ('number_of_plants_ordered', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nursery', models.CharField(max_length=255)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plants')),
            ],
        ),
    ]
